apiVersion: apps/v1
kind: Deployment
metadata:
  name: krakend
  namespace: ilay
spec:
  replicas: 1
  selector:
    matchLabels:
      app: krakend
  template:
    metadata:
      labels:
        app: krakend
    spec:
      containers:
        - name: krakend
          image: devopsfaith/krakend:2
          args: ["run", "-c", "/etc/krakend/krakend.json"]
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: krakend-config
              mountPath: /etc/krakend
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /__health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /__health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 20
      volumes:
        - name: krakend-config
          configMap:
            name: krakend-config
