apiVersion: apps/v1
kind: Deployment
metadata:
  name: developer-application
  namespace: ilay
spec:
  replicas: 1
  selector:
    matchLabels:
      app: developer-application
  template:
    metadata:
      labels:
        app: developer-application
    spec:
      containers:
        - name: developer-application
          image: ghcr.io/ilyavorwork/developer-application:1.0.2
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: common-config
          env:
            - name: POSTGRES_DB
              value: "developer_application"
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: username
            - name: POSTGRES_PASS
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-secret
                  key: access-key
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-secret
                  key: secret-key
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /rk/v1/ready
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /rk/v1/alive
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
