apiVersion: v1
kind: Service
metadata:
  name: developer-application
  namespace: appstore
spec:
  selector:
    app: developer-application
  ports:
    - name: http
      port: 8080
      targetPort: 8080
