apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: appdestr-ingress
  namespace: ilay
  labels:
    app: appdestr
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    nginx.ingress.kubernetes.io/proxy-body-size: "200m"
    nginx.ingress.kubernetes.io/use-gzip: "true"
    nginx.ingress.kubernetes.io/gzip-types: "text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript image/svg+xml application/vnd.android.package-archive"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - appdestr.sergeyhook.ru
      secretName: appdestr-gateway-tls
  rules:
    - host: appdestr.sergeyhook.ru
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: appdestr-svc
                port:
                  number: 80