apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: appstore
type: Opaque
data:
  username: cm9vdA==    # root
  password: cm9vdA==    # root
---
apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  namespace: appstore
type: Opaque
data:
  access-key: bWluaW8=        # minio
  secret-key: bWluaW8xMjM=    # minio123
