apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: swagger-ingress
  namespace: ilay
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - appdistr.sergeyhook.ru
      secretName: appdistr-gateway-tls
  rules:
    - host: appdistr.sergeyhook.ru
      http:
        paths:
          - path: /human/sw
            pathType: Prefix
            backend:
              service:
                name: human-verification
                port:
                  number: 8080
          - path: /devapp/sw
            pathType: Prefix
            backend:
              service:
                name: developer-application
                port:
                  number: 8080
          - path: /devprofile/sw
            pathType: Prefix
            backend:
              service:
                name: developer-profile
                port:
                  number: 8080
