apiVersion: apps/v1
kind: Deployment
metadata:
  name: virus-verification
  namespace: ilay
spec:
  replicas: 1
  selector:
    matchLabels:
      app: virus-verification
  template:
    metadata:
      labels:
        app: virus-verification
    spec:
      nodeSelector:
        kubernetes.io/hostname: worker01
      containers:
        - name: virus-verification
          image: ghcr.io/ilyavorwork/virus-verification:1.0.0
          imagePullPolicy: Always
          # Kafka-only consumer — HTTP-порт не нужен
          envFrom:
            - configMapRef:
                name: common-config
          env:
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-secret
                  key: access-key
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-secret
                  key: secret-key
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
