apiVersion: v1
kind: Service
metadata:
  name: human-verification
  namespace: appstore
spec:
  selector:
    app: human-verification
  ports:
    - name: http
      port: 8080
      targetPort: 8080
