apiVersion: apps/v1
kind: Deployment
metadata:
  name: developer-profile
  namespace: ilay
spec:
  replicas: 1
  selector:
    matchLabels:
      app: developer-profile
  template:
    metadata:
      labels:
        app: developer-profile
    spec:
      containers:
        - name: developer-profile
          image: ghcr.io/ilyavorwork/developer-profile:1.0.2
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: common-config
          env:
            - name: POSTGRES_DB
              value: "developer_profile"
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: username
            - name: POSTGRES_PASS
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /rk/v1/ready
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /rk/v1/alive
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
