apiVersion: apps/v1
kind: Deployment
metadata:
  name: android-emulator
  namespace: ilay
spec:
  replicas: 1
  selector:
    matchLabels:
      app: android-emulator
  template:
    metadata:
      labels:
        app: android-emulator
    spec:
      nodeSelector:
        kubernetes.io/hostname: worker02
      containers:
        - name: android-emulator
          image: budtmo/docker-android:emulator_11.0
          ports:
            - containerPort: 5554
            - containerPort: 5555  # ADB
          env:
            - name: EMULATOR_DEVICE
              value: "Samsung Galaxy S10"
            - name: EMULATOR_TIMEOUT
              value: "300"
          securityContext:
            privileged: true
          volumeMounts:
            - name: kvm
              mountPath: /dev/kvm
          resources:
            requests:
              memory: "2Gi"
              cpu: "1"
            limits:
              memory: "6Gi"
              cpu: "2"
      volumes:
        - name: kvm
          hostPath:
            path: /dev/kvm
