apiVersion: v1
kind: Service
metadata:
  name: android-emulator
  namespace: ilay
spec:
  selector:
    app: android-emulator
  ports:
    - name: adb
      port: 5555
      targetPort: 5555
    - name: novnc
      port: 6080
      targetPort: 6080
