apiVersion: v1
kind: Service
metadata:
  name: auto-verification
  namespace: ilay
spec:
  selector:
    app: auto-verification
  ports:
    - name: grpc
      port: 8080
      targetPort: 8080
    - name: http-gateway
      port: 8081
      targetPort: 8081
